# Generated by Django 4.2 on 2023-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='Videos/thumbnals'),
        ),
    ]
