# Generated by Django 4.2 on 2023-08-30 02:56

from django.db import migrations, models
import django.db.models.deletion
import media_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_api_app', '0003_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='PDF/thumbnals')),
                ('audiofile', models.FileField(upload_to=media_api_app.models.PDFfile.pdf_upload_path)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='media_api_app.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pdf', to='media_api_app.userprofile')),
            ],
        ),
    ]
