# Generated by Django 4.2 on 2023-08-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_api_app', '0004_pdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='audiofile',
            new_name='pdf_file',
        ),
    ]
